apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-vote-back
        env: prod
    spec:
      containers:
      - name: azure-vote-back
        image: redis
#        resources:
#          requests:
#            cpu: "0.15"
#            memory: 256Mi
#          limits:
#            memory: 512Mi
#            cpu: "0.25"
        ports:
        - containerPort: 6379
          name: redis      
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-vote-front
        env: prod
    spec:
      containers:
      - name: azure-vote-front
        image: microsoft/azure-vote-front:v1
#        resources:
#          requests:
#            cpu: "0.15"
#            memory: 256Mi
#          limits:
#            memory: 512Mi
#            cpu: "0.25"
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front
