apiVersion: v1
kind: Service
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  ports:
  - port: 8080
    name: web

  clusterIP: None
  selector:
    app: kuard
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      app: kuard 
  replicas: 2
  template:
    metadata:
      labels:
        app: kuard 
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        ports:
        - containerPort: 8080


