apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheatsheet
  labels:
    app: cheatsheet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheatsheet
template:
  metadata:
    labels:
      app: cheatsheet      
  spec:
  # volumes:
  #   - name: fagdag
  #     azureFile:
  #       secretName: azure-secret
  #       shareName: fagdag
  #       readOnly: true
    #volumes:
    #  - name: fagdagdisk
    #    persistentVolumeClaim:
    #      claimName: fagdagdisk
    containers:
    - name: cheatsheet
      image: sonatconsulting/kubernetes-cheat:0.8
      ports:
      - containerPort: 80
        name: web    
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
    #  volumeMounts:
    #    - name: fagdag
    #      mountPath: /usr/share/nginx/html
 

        