apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: version
  labels:
    app: version
spec:
  replicas: 1
  selector:
    matchLabels:
      app: version
  template:
    metadata:
      labels:
        app: version      
    spec:
      containers:
      - name: version
        image: sonatconsulting/version:1.0
        ports:
        - containerPort: 5000
          name: web    
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: version
spec:
  type: ClusterIP
  ports:
  - port: 5000
  selector:
    app: version
